import { Toolbar, Typography, Button, Paper, Link as MuiLink, AppBar, Grid } from "@mui/material"
import Head from "next/head"
import Link from "next/link"
import Image from "next/image"


const Header = () => {

    return (
        <>
            <Head>
                <title>Monas</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <AppBar
                position="static"
                color="transparent"
                elevation={0}
                sx={{ borderBottom: (theme) => `1px solid ${theme.palette.divider}` }}
            >

                <Toolbar
                    id="back-to-top-anchor"
                    sx={{
                        flexWrap: 'wrap'
                    }}>

                    <MuiLink
                        component={Link}
                        href='/'
                        noWrap sx={{ flexGrow: 1 }}
                    >
                        <Image
                            priority
                            src={'logo-monas_adobe_express.svg'}
                            alt='monas-icon'
                            height={50}
                            width={50}
                        />
                    </MuiLink>

                    <nav>
                        <MuiLink
                            component={Link}
                            variant="button"
                            color="primary"
                            underline="hover"
                            fontWeight={800}
                            href="/history"
                            sx={{ mx: 1.5 }}
                        >
                            Sejarah
                        </MuiLink>


                        <MuiLink
                            component={Link}
                            variant="button"
                            color="primary"
                            underline="hover"
                            fontWeight={800}
                            href="/place"
                            sx={{ mx: 1.5 }}
                        >
                            Wisata
                        </MuiLink>

                        <MuiLink
                            component={Link}
                            fontWeight={800}
                            variant="button"
                            color="primary"
                            underline="hover"
                            href="/ticket"
                            sx={{ mx: 1.5 }}
                        >
                            Tiket
                        </MuiLink>
                    </nav>

                </Toolbar>
            </AppBar>

        </>
    )
}

export default Header