import { Toolbar, Typography, Button, Paper } from "@mui/material"
import Head from "next/head"
import Link from "next/link"
import Image from "next/image"

const Header = () => {

    return (
        <>
            <Head>
                <title>Monas</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Toolbar id="back-to-top-anchor" sx={{ borderBottom: 1, borderColor: 'divider' }}>

                <Link
                    href='/'
                >
                    <Image
                        priority
                        src={'logo-monas_adobe_express.svg'}
                        alt='monas-icon'
                        height={40}
                        width={40}
                    />
                </Link>

            </Toolbar>


        </>
    )
}

export default Header